language: java
jdk:
  - openjdk8

branches:
  only:
    - master

after_success:
  - ./gradlew jacocoTestReport coveralls

env:
  global:
    # COVERALLS_REPO_TOKEN
    secure: QJS5AXc7gj+IWl0LrQScYN+khsVE9BMcGJL5wYdOJmqItnlwjsKO5dzNsNCrvPDRgkTtcuypmP93qnvq/6VPaLG9jkV66LKqadGKO6Q2dp+noWAx+8fsREcraDx8N5Axy5o9Q9+6NSz57VHIXbm6jc18B6tOgw6GuA3VEdp++BRTRe+qiliM6PGxy91FcUc+chtu9PSJajTJAmXBpxylZkdnRJ5rAfqiv7ynP04p7j60g7LnmNEVYPmJ3PaQ4YJdy4Bzq6f2ZFsMFInYaUjha2eJSk9O/69yhfdMQ/bS0UcU/5O8CEb6St8k7pmwYzYkTz4P51ki3If5GbwSdcpcg735UwRflD0ci96vBBQaxiiFHTk36yHflSvrz4kJ3TvSXvrJnkm74O8uMnKg0fuNdQpEpa9iLLMoIq4DN9CWaPc0aAwG8modO85GBSAEpxh0X0R1AGnF52rUlfYLuLwLha5ngEE+wN5p/0+EynD1ACT3c9jJ0yVit02nqQ6R2i6o9pQCPbotMom+LrANASlMS5qoEIJVdwefbgI1l0Nn4d3pRK3HSXBcTtO90i2KHD3iV3iXiswgKuX+Wv0nRtvjj4r2xdyLuomqRz087mUdiy8jddCU0vvQhO5Ixv4DhNf2eVzE2psB6IuW4KYWr4cV3xyczJCyyhs2RxcWvYimvIo=
